FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block keepalived_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{# ppc64le: the MariaDB repos have no working ppc64el debs, so fall back to
   Debian's native mariadb-client instead of enabling the MariaDB repo. #}
{% if base_arch != 'ppc64le' %}
{{ macros.enable_extra_repos(['mariadb']) }}
{% endif %}

{% if base_package_type == 'rpm' %}
    {% set keepalived_packages = [
        'keepalived',
        'MariaDB-client'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set keepalived_packages = [
        'keepalived',
        'mariadb-client'
    ] %}
{% endif %}
{{ macros.install_packages(keepalived_packages | customizable("packages")) }}

COPY check_alive.sh /

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 644 /usr/local/bin/kolla_extend_start \
    && chmod 755 /check_alive.sh

{{ macros.kolla_patch_sources() }}

{% block keepalived_footer %}{% endblock %}
{% block footer %}{% endblock %}
