{% if base_arch == 'ppc64le' %}
# Build stage for ppc64le - build from source
# cadvisor v0.53.0 requires Go 1.23+
FROM golang:1.25-trixie AS builder

ARG CADVISOR_VERSION=v0.53.0
RUN git clone --depth 1 --branch ${CADVISOR_VERSION} https://github.com/google/cadvisor.git /go/src/github.com/google/cadvisor
WORKDIR /go/src/github.com/google/cadvisor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -o /cadvisor ./cmd/cadvisor

{% endif %}
FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block prometheus_cadvisor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block prometheus_cadvisor_install %}
{% if base_arch == 'ppc64le' %}
COPY --from=builder /cadvisor /opt/cadvisor
RUN chmod 0755 /opt/cadvisor
{% else %}
ADD prometheus-cadvisor-archive /prometheus-cadvisor-source

RUN cp /prometheus-cadvisor-source /opt/cadvisor \
    && chmod 0755 /opt/cadvisor
{% endif %}
{% endblock %}

{{ macros.kolla_patch_sources() }}

{% block prometheus_cadvisor_footer %}{% endblock %}
{% block footer %}{% endblock %}
