{% if base_arch == 'ppc64le' %}
FROM {{ base_image }}:{{ base_distro_tag }} AS proxysql-builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config cmake g++ gcc git \
    libssl-dev libgnutls28-dev default-libmysqlclient-dev \
    uuid-dev libncurses-dev libicu-dev libevent-dev \
    ca-certificates automake bzip2 python3
WORKDIR /build
RUN git clone --depth 1 --branch v2.7.1 \
    https://github.com/sysown/proxysql.git
WORKDIR /build/proxysql
RUN make -j$(nproc)
{% endif %}

FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block proxysql_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_arch == 'ppc64le' %}

{% set proxysql_packages = [
    'python3-yaml',
    'libgnutls30t64',
    'libmariadb3',
    'libunwind8',
] %}

{{ macros.configure_user(name='proxysql') }}
{{ macros.install_packages(proxysql_packages | customizable("packages")) }}

COPY --from=proxysql-builder /build/proxysql/src/proxysql /usr/bin/proxysql
RUN chmod 755 /usr/bin/proxysql

{% else %}

{{ macros.enable_extra_repos(['proxysql']) }}

{% set proxysql_packages = [
    'proxysql',
] %}

{% if base_package_type == 'rpm' %}
    {% set proxysql_packages = proxysql_packages + [
        'python3-PyYAML',
    ] %}
{% elif base_package_type == 'deb' %}
    {% set proxysql_packages = proxysql_packages + [
        'python3-yaml',
    ] %}
{% endif %}

{{ macros.configure_user(name='proxysql') }}
{{ macros.install_packages(proxysql_packages | customizable("packages")) }}

{% endif %}

COPY kolla_proxysql_config_sync kolla_extend_start /usr/local/bin/
RUN chmod 755 /usr/local/bin/kolla_proxysql_config_sync \
    && chmod 644 /usr/local/bin/kolla_extend_start

RUN install -g proxysql -o proxysql -m 770 -d /var/lib/kolla/proxysql \
    && touch /etc/proxysql.cnf \
    && chown proxysql:proxysql /etc/proxysql.cnf \
    && chmod 600 /etc/proxysql.cnf

{{ macros.kolla_patch_sources() }}

{% block proxysql_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER proxysql
